### PR TITLE
Faction chat initial

### PR DESCRIPTION
**Pull request by Intueor**

### CODE REVIEW

**Comment by Spcemarine** [comment]
Could you move the broadcasting and the faction chat into separate commands? This will allow admins to make proper use of the permission system and it will provide better usability to the mod as both the help and the documentation can be separated from rather unrelated features. Also it'll be better for the internal structure of the mod as "CommandPrivateMessage" does not imply faction chat etc. So if you could do that I'd approve of this addition.

**Comment by Intueor** [comment]
Yes, I completely agree with your arguments and wishes. A new variant of whole mod has been tested on my own server, all new functions works well. But there is only one doubtful aspect about help texts - my English is dilettantish, so if you could do some checks, it will be fine.

**Comment by Spcemarine** [comment]
Don't worry about the help texts. As long as all features are mentioned we can improve it if necessary. One (hopefully last) question: The '+' feature is an approach to implement a chat room like thing and makes more sense if the global chat is deactivated, right?

**Comment by Intueor** [comment]
Exactly. It is a compromise between the uncontrollable global chat and a complete lack of team communication. On our server, this 'chat room' was founded by dummy player and accepts peace by default. Also, there is a faction for beginners, which is friendly with CHT and accepts all comers.

I understand that it could be implemented at the program level for each player (with saving in personal settings), but I do not know so deep the code of your mod and SE code as a whole at the moment.
My aim at the near past was been to save the server from trolls and filthy language in global chat.

**Comment by Spcemarine** [comment]
I made quite a few changes in 7c61aa8870aef0456a1176b7471b284717540f25. I hope you are ok with that. Please let me know if there is anything wrong with it.

I removed the logging because it'd create entries in the private message log for each message that is sent. So if you have like 10 receivers it'd create 10 entries with exactly the same content except for the receiver. In my view that's bad so I removed it. We can still implement a proper log later. Also I think there was a huge error in the logic of sending messages to factions with more than one or two players as you had a `break` statement in the loop that goes through all members of the faction that'll cancel the loop if the message was sent to a player. Did you ever experience that kind of bug?

**Comment by Intueor** [comment]
Thank you a lot for your fixes! I started working with C # near a month ago, before - (about 5 years) only C++, thereby there's totally defferent style.
It is strange, but I do not have any messages from players about the bugs in the script, may be they just was not sends any answer. But you are right, it is a my fail (with 'break' statement). All is ok, thanks again.

**Comment by Spcemarine** [comment]
I assume by personal chat history you mean a history of chat messages that were addressed at the player requesting it? If we'd create a separate log for the faction chat it'll be easy to create such a personal chat history. We'll just have to filter which messages were (or would have been) sent to the client requesting the chat history, bring them into correct order and then send it to the client. Would be a nice addition to /chat.

**Comment by Intueor** [comment]
Yes, that is what I mean. But there are some variants, i think. For example, all players will have a separate 'point of view' to whole chat hystory depends of their relations. Or, as you said, each faction will have a separate hystory, but it may be slightly floody for filesistem in my opinion.

**Comment by Spcemarine** [comment]
On second thought it's not as easy as I thought it would be because the relations between players and factions can change and the relations among factions can change. So it's not clear if a player would have received a certain message that was sent to his faction some days ago because we can't assume that he was already a member of that faction by the time the message was sent. So this approach will only work for the private messages. Or, in terms of a faction chat log, we could store a list of steamIds to which the massage would have been sent if all players were online... Depends on how we implement the log.

**Pull request merged**
